server:
  port: 0
  error:
    include-message: always
    include-binding-errors: always

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-application
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/online_market
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
